<?php

/*

 Add BigFish Games Catalog for WordPress
 ==============================================================================

This plugin adds game catalog from http://www.bigfishgames.com/?afcode=afd63cd4ad992 to your Blog.

Support of all known types of games: PC, Macintosh, FREE Online games.
Also 5 languages (English, German, Spanish, French, Japanese) are supported all!

The plugin keeps some part of the data in metafields.
If you wish to receive an example how to deduce the data of metafields in template WordPress you need to become my referral BigFishGames.
Under this reference https://pnp.bigfishgames.com/?afcode=afd63cd4ad992 you can become my referral.
If you are already registered in BigFishGames that you can buy a ready template.
The price of a template of $100. Payment is possible through system WebMoney (Z231409672156).
Plus to a template you can receive an additional script cron.php which will automatically add new games without your participation!
If you became my referral, or have paid, for reception of additional files write on an e-mail isestnestmi@mail.ru or ICQ 338900566
To write to me it is necessary in English or in Russian. I do not know other languages!

                See example at http://BigFishTest.com/ or http://www.ShuvaevGames.com
*/

$bfg_min_rating = 1000000000;
$bfg_start_date = '2000-01-01';
$bfg_cache_lifetime = 1;
$bfg_cron = 'bfg_timly';
$bfg_cache_path = dirname(__FILE__).'/_cache/';

$bfg_post = array(
	'post_title' => '{GAMENAME}',
	'post_name' => '{GAMENAME}',
	'post_excerpt' => '{SHORTDESC}',
	'post_content' => '{LONGDESC}',
	'post_status' => 'publish'
);

$bfg_images = array(
	'SMALL' => 'images/{POSTNAME}-small.jpg',
	'MED' => 'images/{POSTNAME}-med.jpg',
	'SUBFEATURE' => 'images/{POSTNAME}-subfeature.jpg',
	'FEATURE' => 'images/{POSTNAME}-feature.jpg',
	'THUMB1' => 'images/{POSTNAME}-thumb1.jpg',
	'THUMB2' => 'images/{POSTNAME}-thumb2.jpg',
	'SCREEN1' => 'images/{POSTNAME}-screen1.jpg',
	'SCREEN2' => 'images/{POSTNAME}-screen2.jpg'
	);
$bfg_images_jp = array(
	'SMALL' => 'images/{FOLDERNAME}-small.jpg',
	'MED' => 'images/{FOLDERNAME}-med.jpg',
	'SUBFEATURE' => 'images/{FOLDERNAME}-subfeature.jpg',
	'FEATURE' => 'images/{FOLDERNAME}-feature.jpg',
	'THUMB1' => 'images/{FOLDERNAME}-thumb1.jpg',
	'THUMB2' => 'images/{FOLDERNAME}-thumb2.jpg',
	'SCREEN1' => 'images/{FOLDERNAME}-screen1.jpg',
	'SCREEN2' => 'images/{FOLDERNAME}-screen2.jpg'
	);
$bfg_add_meta = array(
	'GAMEID' => 'bfg_gameid',
	'BULLET1' => 'bfg_bullet1',
	'BULLET2' => 'bfg_bullet2',
	'BULLET3' => 'bfg_bullet3',
	'BULLET4' => 'bfg_bullet4',
	'BULLET5' => 'bfg_bullet5',
	'FOLDERNAME' => 'bfg_foldername',
	'DOWNLOADIFRAME' => 'bfg_downloadiframe',
	'BUYIFRAME' => 'bfg_buyiframe',
	'GAMERANK' => 'bfg_gamerank',
	'GAMESIZE' => 'bfg_gamesize',
	'SYSREQOS' => 'bfg_sysreqos',
	'SYSREQMHZ' => 'bfg_sysreqmhz',
	'SYSREQDX' => 'bfg_sysreqdx',
	'SYSREQVIDEO' => 'bfg_sysreqvideo',
	'SYSREQHD' => 'bfg_sysreqhd'
	);
$bfg_update_meta = array(
	'GAMERANK' => 'bfg_gamerank'
	);

$bfg_genres = array(
	'1' => array('name' => 'Action & Arcade', 'sname' => 'action', 'isPri' => 'yes'),
	'2' => array('name' => 'Jigsaw', 'sname' => 'jigsaw', 'isPri' => 'no'),
	'3' => array('name' => 'Mahjong', 'sname' => 'mahjong', 'isPri' => 'yes'),
	'4' => array('name' => 'Puzzle', 'sname' => 'puzzle', 'isPri' => 'yes'),
	'5' => array('name' => 'Card & Board', 'sname' => 'card', 'isPri' => 'yes'),
	'6' => array('name' => 'Word', 'sname' => 'word', 'isPri' =>  'yes'),
	'7' => array('name' => 'Multiplayer', 'sname' =>  'multiplayer', 'isPri' => 'no'),
	'9' => array('name' => 'Broadband', 'sname' => 'broadband', 'isPri' => 'no'),
	'10' => array('name' => 'Sports', 'sname' =>  'sports', 'isPri' => 'no'),
	'11' => array('name' => 'Casino', 'sname' => 'casino', 'isPri' => 'no'),
	'14' => array('name' => 'Game of the Year', 'sname' => 'game', 'isPri' => 'no'),
	'15' => array('name' => 'Hidden Object', 'sname' => 'hidden', 'isPri' => 'yes'),
	'16' => array('name' => 'Mac', 'sname' => 'mac', 'isPri' => 'no'),
	'17' => array('name' => 'Match 3', 'sname' => 'match3', 'isPri' => 'yes'),
	'18' => array('name' => 'Marble Popper', 'sname' => 'marble', 'isPri' => 'yes'),
	'19' => array('name' => 'Brain Teaser', 'sname' => 'brain', 'isPri' => 'yes'),
	'20' => array('name' => 'Large File Adventure', 'sname' => 'adventure_large', 'isPri' => 'yes'),
	'21' => array('name' => 'Adventure', 'sname' => 'adventure', 'isPri' => 'yes'),
	'22' => array('name' => 'Brick Buster', 'sname' => 'brick', 'isPri' => 'no'),
	'23' => array('name' => 'Platformer', 'sname' => 'platformer', 'isPri' => 'no'),
	'24' => array('name' => 'Shooter', 'sname' => 'shooter', 'isPri' => 'no'),
	'25' => array('name' => 'Time Management', 'sname' => 'time', 'isPri' => 'yes'),
	'26' => array('name' => 'Kids', 'sname' => 'kids', 'isPri' => 'yes'),
	'27' => array('name' => 'Mystery', 'sname' => 'mystery', 'isPri' => 'no'),
	'29' => array('name' => 'Strategy', 'sname' => 'strategy', 'isPri' => 'yes'),
	'30' => array('name' => 'Riddle', 'sname' => 'riddle', 'isPri' => 'yes'),
	'31' => array('name' => '3D', 'sname' => '3d', 'isPri' => 'no'),
	'32' => array('name' => 'Animal', 'sname' => 'animal', 'isPri' => 'no'),
	'33' => array('name' => 'Baking', 'sname' => 'baking', 'isPri' => 'no'),
	'34' => array('name' => 'Beauty', 'sname' => 'beauty', 'isPri' => 'no'),
	'35' => array('name' => 'Book', 'sname' => 'book', 'isPri' => 'no'),
	'36' => array('name' => 'Bowling', 'sname' => 'bowling', 'isPri' => 'no'),
	'37' => array('name' => 'Breakout', 'sname' => 'breakout', 'isPri' => 'no'),
	'38' => array('name' => 'Building', 'sname' => 'building', 'isPri' => 'no'),
	'39' => array('name' => 'Burger', 'sname' => 'burger', 'isPri' => 'no'),
	'40' => array('name' => 'Candy', 'sname' => 'candy', 'isPri' => 'no'),
	'41' => array('name' => 'Cat', 'sname' => 'cat', 'isPri' => 'no'),
	'42' => array('name' => 'Chess', 'sname' => 'chess', 'isPri' => 'no'),
	'43' => array('name' => 'Chicken', 'sname' => 'chicken', 'isPri' => 'no'),
	'44' => array('name' => 'Childrens', 'sname' => 'childrens', 'isPri' => 'no'),
	'45' => array('name' => 'Christmas', 'sname' => 'christmas', 'isPri' => 'no'), 
	'46' => array('name' => 'Classic', 'sname' => 'classic', 'isPri' => 'no'),
	'47' => array('name' => 'Cooking', 'sname' => 'cooking', 'isPri' => 'no'),
	'48' => array('name' => 'Dancing', 'sname' => 'dancing', 'isPri' => 'no'),
	'49' => array('name' => 'Detective', 'sname' => 'detective', 'isPri' => 'no'),
	'50' => array('name' => 'Doctor', 'sname' => 'doctor', 'isPri' => 'no'),
	'51' => array('name' => 'Dog', 'sname' => 'dog', 'isPri' => 'no'),
	'52' => array('name' => 'Dominos', 'sname' => 'dominos', 'isPri' => 'no'),
	'53' => array('name' => 'Dragon', 'sname' => 'dragon', 'isPri' => 'no'),
	'54' => array('name' => 'Dress Up', 'sname' => 'dress_up', 'isPri' => 'no'),
	'55' => array('name' => 'Educational', 'sname' => 'educational', 'isPri' => 'no'),
	'56' => array('name' => 'Fairy', 'sname' => 'fairy', 'isPri' => 'no'),
	'57' => array('name' => 'Fantasy', 'sname' => 'fantasy', 'isPri' => 'no'),
	'58' => array('name' => 'Farm', 'sname' => 'farm', 'isPri' => 'no'),
	'59' => array('name' => 'Fashion', 'sname' => 'fashion', 'isPri' => 'no'),
	'60' => array('name' => 'Flower', 'sname' => 'flower', 'isPri' => 'no'),
	'61' => array('name' => 'Food', 'sname' => 'food', 'isPri' => 'no'),
	'62' => array('name' => 'Game Show', 'sname' => 'game_show', 'isPri' => 'no'),
	'63' => array('name' => 'Garden', 'sname' => 'garden', 'isPri' => 'no'),
	'64' => array('name' => 'Holiday', 'sname' => 'holiday', 'isPri' => 'no'),
	'65' => array('name' => 'Hotel', 'sname' => 'hotel', 'isPri' => 'no'),
	'66' => array('name' => 'Ice Cream', 'sname' => 'ice_cream', 'isPri' => 'no'),
	'67' => array('name' => 'Interior Design', 'sname' => 'interior_design', 'isPri' => 'no'),
	'68' => array('name' => 'Jewelry', 'sname' => 'jewelry', 'isPri' => 'no'),
	'69' => array('name' => 'Magic', 'sname' => 'magic', 'isPri' => 'no'),
	'70' => array('name' => 'Monster', 'sname' => 'monster', 'isPri' => 'no'),
	'71' => array('name' => 'Music', 'sname' => 'music', 'isPri' => 'no'),
	'72' => array('name' => 'Pet', 'sname' => 'pet', 'isPri' => 'no'),
	'73' => array('name' => 'Pirate', 'sname' => 'pirate', 'isPri' => 'no'),
	'74' => array('name' => 'Plant', 'sname' => 'plant', 'isPri' => 'no'),
	'75' => array('name' => 'Point And Click', 'sname' => 'point_and_click', 'isPri' => 'no'),
	'76' => array('name' => 'Poker', 'sname' => 'poker', 'isPri' => 'no'),
	'77' => array('name' => 'Princess', 'sname' => 'princess', 'isPri' => 'no'),
	'78' => array('name' => 'Quest', 'sname' => 'quest', 'isPri' => 'no'),
	'79' => array('name' => 'Racing', 'sname' => 'racing', 'isPri' => 'no'),
	'80' => array('name' => 'Real Time', 'sname' => 'real_time', 'isPri' => 'no'),
	'81' => array('name' => 'Restaurant', 'sname' => 'restaurant', 'isPri' => 'no'),
	'82' => array('name' => 'Rpg', 'sname' => 'rpg', 'isPri' => 'no'),
	'83' => array('name' => 'Seek And Find', 'sname' => 'seek_and_find', 'isPri' => 'no'),
	'84' => array('name' => 'Sim', 'sname' => 'sim', 'isPri' => 'no'),
	'85' => array('name' => 'Solitaire', 'sname' => 'solitaire', 'isPri' => 'no'),
	'86' => array('name' => 'Spa', 'sname' => 'spa', 'isPri' => 'no'),
	'87' => array('name' => 'Space', 'sname' => 'space', 'isPri' => 'no'),
	'88' => array('name' => 'Sudoku', 'sname' => 'sudoku', 'isPri' => 'no'),
	'89' => array('name' => 'Tower Defense', 'sname' => 'tower_defense', 'isPri' => 'no'),
	'90' => array('name' => 'Travel', 'sname' => 'travel', 'isPri' => 'no'),
	'91' => array('name' => 'Treasure', 'sname' => 'treasure', 'isPri' => 'no'),
	'92' => array('name' => 'Trivia', 'sname' => 'trivia', 'isPri' => 'no'),
	'93' => array('name' => 'Tv Show', 'sname' => 'tv_show', 'isPri' => 'no'),
	'94' => array('name' => 'Tycoon', 'sname' => 'tycoon', 'isPri' => 'no'),
	'95' => array('name' => 'War', 'sname' => 'war', 'isPri' => 'no'),
	'96' => array('name' => 'Water', 'sname' => 'water', 'isPri' => 'no'),
	'97' => array('name' => 'Wedding', 'sname' => 'wedding', 'isPri' => 'no'),
	'98' => array('name' => 'Zoo', 'sname' => 'zoo', 'isPri' => 'no'),
	'99' => array('name' => 'Agatha Christie', 'sname' => 'agatha_christie', 'isPri' => 'no'),
	'100' => array('name' => 'Aveyond', 'sname' => 'aveyond', 'isPri' => 'no'),
	'101' => array('name' => 'Beetle Bug', 'sname' => 'beetle_bug', 'isPri' => 'no'),
	'102' => array('name' => 'Diner Dash', 'sname' => 'diner_dash', 'isPri' => 'no'),
	'103' => array('name' => 'Dora The Explorer', 'sname' => 'dora_the_explorer', 'isPri' => 'no'),
	'104' => array('name' => 'Dream Day', 'sname' => 'dream_day', 'isPri' => 'no'),
	'105' => array('name' => 'Luxor', 'sname' => 'luxor', 'isPri' => 'no'),
	'106' => array('name' => 'Nancy Drew', 'sname' => 'nancy_drew', 'isPri' => 'no'),
	'107' => array('name' => 'Pat Sajak', 'sname' => 'pat_sajak', 'isPri' => 'no'),
	'108' => array('name' => 'Ricochet', 'sname' => 'ricochet', 'isPri' => 'no'),
	'109' => array('name' => 'Sherlock Holmes', 'sname' => 'sherlock_holmes', 'isPri' => 'no'),
	'110' => array('name' => 'Sims Carnival', 'sname' => 'sims_carnival', 'isPri' => 'no'),
	'111' => array('name' => 'Slingo', 'sname' => 'slingo', 'isPri' => 'no'),
	'112' => array('name' => 'Spongebob', 'sname' => 'spongebob', 'isPri' => 'no'),
	'113' => array('name' => 'Tri Peaks', 'sname' => 'tri_peaks', 'isPri' => 'no'),
	'114' => array('name' => 'Virtual Villagers', 'sname' => 'virtual_villagers', 'isPri' => 'no'),
	'115' => array('name' => 'Azada', 'sname' => 'azada', 'isPri' => 'no'),
	'116' => array('name' => 'Hidden Expedition', 'sname' => 'hidden_expedition', 'isPri' => 'no'),
	'117' => array('name' => 'Mystery Case Files', 'sname' => 'mystery_case_files', 'isPri' => 'no'),
	'118' => array('name' => 'Best PC', 'sname' => 'best_pc', 'isPri' => 'no'),
	'119' => array('name' => 'Exclusive', 'sname' => 'exclusive', 'isPri' => 'no')
);

$bfg_genres_de = array(
	'1' => array('name' => 'Action & Arcade', 'sname' => 'action', 'isPri' => 'yes'),
	'2' => array('name' => 'Spalts&#228;ge', 'sname' => 'spaltsage', 'isPri' => 'no'),
	'3' => array('name' => 'Mahjong', 'sname' => 'mahjong', 'isPri' => 'yes'),
	'4' => array('name' => 'Puzzle', 'sname' => 'puzzle', 'isPri' => 'yes'),
	'5' => array('name' => 'Karten- &amp; Brett', 'sname' => 'karten-brett', 'isPri' => 'yes'),
	'6' => array('name' => 'Worträtsel', 'sname' => 'wort', 'isPri' =>  'yes'),
	'7' => array('name' => 'Multiplayer', 'sname' =>  'multiplayer', 'isPri' => 'no'),
	'9' => array('name' => 'Broadband', 'sname' => 'broadband', 'isPri' => 'no'),
	'10' => array('name' => 'Sports', 'sname' =>  'sports', 'isPri' => 'no'),
	'11' => array('name' => 'Kasino', 'sname' => 'kasino', 'isPri' => 'yes'),
	'14' => array('name' => 'Game of the Year', 'sname' => 'game', 'isPri' => 'no'),
	'15' => array('name' => 'Wimmelbild', 'sname' => 'wimmelbilder', 'isPri' => 'yes'),
	'16' => array('name' => 'Mac', 'sname' => 'mac', 'isPri' => 'no'),
	'17' => array('name' => '3-Gewinnt', 'sname' => 'match3', 'isPri' => 'yes'),
	'18' => array('name' => 'Murmel', 'sname' => 'murmelspiele', 'isPri' => 'yes'),
	'19' => array('name' => 'Denksport', 'sname' => 'denksport', 'isPri' => 'yes'),
	'20' => array('name' => 'Breitband', 'sname' => 'breitband', 'isPri' => 'yes'),
	'21' => array('name' => 'Abenteuer', 'sname' => 'abenteuer', 'isPri' => 'yes'),
	'22' => array('name' => 'Brick Buster', 'sname' => 'brick', 'isPri' => 'no'),
	'23' => array('name' => 'Platformer', 'sname' => 'platformer', 'isPri' => 'no'),
	'24' => array('name' => 'Shooter', 'sname' => 'shooter', 'isPri' => 'no'),
	'25' => array('name' => 'Gegen-die-Zeit', 'sname' => 'gegen-die-zeit', 'isPri' => 'yes'),
	'26' => array('name' => 'Kinder', 'sname' => 'kinder', 'isPri' => 'yes'),
	'27' => array('name' => 'Mystery', 'sname' => 'mystery', 'isPri' => 'no'),
	'29' => array('name' => 'Strategie', 'sname' => 'strategie', 'isPri' => 'yes'),
	'30' => array('name' => 'Rätsel', 'sname' => 'raetsel', 'isPri' => 'yes'),
	'31' => array('name' => '3D', 'sname' => '3d', 'isPri' => 'no'),
	'32' => array('name' => 'Animal', 'sname' => 'animal', 'isPri' => 'no'),
	'33' => array('name' => 'Baking', 'sname' => 'baking', 'isPri' => 'no'),
	'34' => array('name' => 'Beauty', 'sname' => 'beauty', 'isPri' => 'no'),
	'35' => array('name' => 'Book', 'sname' => 'book', 'isPri' => 'no'),
	'36' => array('name' => 'Bowling', 'sname' => 'bowling', 'isPri' => 'no'),
	'37' => array('name' => 'Breakout', 'sname' => 'breakout', 'isPri' => 'no'),
	'38' => array('name' => 'Building', 'sname' => 'building', 'isPri' => 'no'),
	'39' => array('name' => 'Burger', 'sname' => 'burger', 'isPri' => 'no'),
	'40' => array('name' => 'Candy', 'sname' => 'candy', 'isPri' => 'no'),
	'41' => array('name' => 'Cat', 'sname' => 'cat', 'isPri' => 'no'),
	'42' => array('name' => 'Chess', 'sname' => 'chess', 'isPri' => 'no'),
	'43' => array('name' => 'Chicken', 'sname' => 'chicken', 'isPri' => 'no'),
	'44' => array('name' => 'Childrens', 'sname' => 'childrens', 'isPri' => 'no'),
	'45' => array('name' => 'Christmas', 'sname' => 'christmas', 'isPri' => 'no'), 
	'46' => array('name' => 'Classic', 'sname' => 'classic', 'isPri' => 'no'),
	'47' => array('name' => 'Cooking', 'sname' => 'cooking', 'isPri' => 'no'),
	'48' => array('name' => 'Dancing', 'sname' => 'dancing', 'isPri' => 'no'),
	'49' => array('name' => 'Detective', 'sname' => 'detective', 'isPri' => 'no'),
	'50' => array('name' => 'Doctor', 'sname' => 'doctor', 'isPri' => 'no'),
	'51' => array('name' => 'Dog', 'sname' => 'dog', 'isPri' => 'no'),
	'52' => array('name' => 'Dominos', 'sname' => 'dominos', 'isPri' => 'no'),
	'53' => array('name' => 'Dragon', 'sname' => 'dragon', 'isPri' => 'no'),
	'54' => array('name' => 'Dress Up', 'sname' => 'dress_up', 'isPri' => 'no'),
	'55' => array('name' => 'Educational', 'sname' => 'educational', 'isPri' => 'no'),
	'56' => array('name' => 'Fairy', 'sname' => 'fairy', 'isPri' => 'no'),
	'57' => array('name' => 'Fantasy', 'sname' => 'fantasy', 'isPri' => 'no'),
	'58' => array('name' => 'Farm', 'sname' => 'farm', 'isPri' => 'no'),
	'59' => array('name' => 'Fashion', 'sname' => 'fashion', 'isPri' => 'no'),
	'60' => array('name' => 'Flower', 'sname' => 'flower', 'isPri' => 'no'),
	'61' => array('name' => 'Food', 'sname' => 'food', 'isPri' => 'no'),
	'62' => array('name' => 'Game Show', 'sname' => 'game_show', 'isPri' => 'no'),
	'63' => array('name' => 'Garden', 'sname' => 'garden', 'isPri' => 'no'),
	'64' => array('name' => 'Holiday', 'sname' => 'holiday', 'isPri' => 'no'),
	'65' => array('name' => 'Hotel', 'sname' => 'hotel', 'isPri' => 'no'),
	'66' => array('name' => 'Ice Cream', 'sname' => 'ice_cream', 'isPri' => 'no'),
	'67' => array('name' => 'Interior Design', 'sname' => 'interior_design', 'isPri' => 'no'),
	'68' => array('name' => 'Jewelry', 'sname' => 'jewelry', 'isPri' => 'no'),
	'69' => array('name' => 'Magic', 'sname' => 'magic', 'isPri' => 'no'),
	'70' => array('name' => 'Monster', 'sname' => 'monster', 'isPri' => 'no'),
	'71' => array('name' => 'Music', 'sname' => 'music', 'isPri' => 'no'),
	'72' => array('name' => 'Pet', 'sname' => 'pet', 'isPri' => 'no'),
	'73' => array('name' => 'Pirate', 'sname' => 'pirate', 'isPri' => 'no'),
	'74' => array('name' => 'Plant', 'sname' => 'plant', 'isPri' => 'no'),
	'75' => array('name' => 'Point And Click', 'sname' => 'point_and_click', 'isPri' => 'no'),
	'76' => array('name' => 'Poker', 'sname' => 'poker', 'isPri' => 'no'),
	'77' => array('name' => 'Princess', 'sname' => 'princess', 'isPri' => 'no'),
	'78' => array('name' => 'Quest', 'sname' => 'quest', 'isPri' => 'no'),
	'79' => array('name' => 'Racing', 'sname' => 'racing', 'isPri' => 'no'),
	'80' => array('name' => 'Real Time', 'sname' => 'real_time', 'isPri' => 'no'),
	'81' => array('name' => 'Restaurant', 'sname' => 'restaurant', 'isPri' => 'no'),
	'82' => array('name' => 'Rpg', 'sname' => 'rpg', 'isPri' => 'no'),
	'83' => array('name' => 'Seek And Find', 'sname' => 'seek_and_find', 'isPri' => 'no'),
	'84' => array('name' => 'Sim', 'sname' => 'sim', 'isPri' => 'no'),
	'85' => array('name' => 'Solitaire', 'sname' => 'solitaire', 'isPri' => 'no'),
	'86' => array('name' => 'Spa', 'sname' => 'spa', 'isPri' => 'no'),
	'87' => array('name' => 'Space', 'sname' => 'space', 'isPri' => 'no'),
	'88' => array('name' => 'Sudoku', 'sname' => 'sudoku', 'isPri' => 'no'),
	'89' => array('name' => 'Tower Defense', 'sname' => 'tower_defense', 'isPri' => 'no'),
	'90' => array('name' => 'Travel', 'sname' => 'travel', 'isPri' => 'no'),
	'91' => array('name' => 'Treasure', 'sname' => 'treasure', 'isPri' => 'no'),
	'92' => array('name' => 'Trivia', 'sname' => 'trivia', 'isPri' => 'no'),
	'93' => array('name' => 'Tv Show', 'sname' => 'tv_show', 'isPri' => 'no'),
	'94' => array('name' => 'Tycoon', 'sname' => 'tycoon', 'isPri' => 'no'),
	'95' => array('name' => 'War', 'sname' => 'war', 'isPri' => 'no'),
	'96' => array('name' => 'Water', 'sname' => 'water', 'isPri' => 'no'),
	'97' => array('name' => 'Wedding', 'sname' => 'wedding', 'isPri' => 'no'),
	'98' => array('name' => 'Zoo', 'sname' => 'zoo', 'isPri' => 'no'),
	'99' => array('name' => 'Agatha Christie', 'sname' => 'agatha_christie', 'isPri' => 'no'),
	'100' => array('name' => 'Aveyond', 'sname' => 'aveyond', 'isPri' => 'no'),
	'101' => array('name' => 'Beetle Bug', 'sname' => 'beetle_bug', 'isPri' => 'no'),
	'102' => array('name' => 'Diner Dash', 'sname' => 'diner_dash', 'isPri' => 'no'),
	'103' => array('name' => 'Dora The Explorer', 'sname' => 'dora_the_explorer', 'isPri' => 'no'),
	'104' => array('name' => 'Dream Day', 'sname' => 'dream_day', 'isPri' => 'no'),
	'105' => array('name' => 'Luxor', 'sname' => 'luxor', 'isPri' => 'no'),
	'106' => array('name' => 'Nancy Drew', 'sname' => 'nancy_drew', 'isPri' => 'no'),
	'107' => array('name' => 'Pat Sajak', 'sname' => 'pat_sajak', 'isPri' => 'no'),
	'108' => array('name' => 'Ricochet', 'sname' => 'ricochet', 'isPri' => 'no'),
	'109' => array('name' => 'Sherlock Holmes', 'sname' => 'sherlock_holmes', 'isPri' => 'no'),
	'110' => array('name' => 'Sims Carnival', 'sname' => 'sims_carnival', 'isPri' => 'no'),
	'111' => array('name' => 'Slingo', 'sname' => 'slingo', 'isPri' => 'no'),
	'112' => array('name' => 'Spongebob', 'sname' => 'spongebob', 'isPri' => 'no'),
	'113' => array('name' => 'Tri Peaks', 'sname' => 'tri_peaks', 'isPri' => 'no'),
	'114' => array('name' => 'Virtual Villagers', 'sname' => 'virtual_villagers', 'isPri' => 'no'),
	'115' => array('name' => 'Azada', 'sname' => 'azada', 'isPri' => 'no'),
	'116' => array('name' => 'Hidden Expedition', 'sname' => 'hidden_expedition', 'isPri' => 'no'),
	'117' => array('name' => 'Mystery Case Files', 'sname' => 'mystery_case_files', 'isPri' => 'no'),
	'118' => array('name' => 'Best PC', 'sname' => 'best_pc', 'isPri' => 'no'),
	'119' => array('name' => 'Exclusive', 'sname' => 'exclusive', 'isPri' => 'no')
);

$bfg_genres_es = array(
	'1' => array('name' => 'Arcade y Acción', 'sname' => 'arcade-y-accion', 'isPri' => 'yes'),
	'2' => array('name' => 'Sierra de vaiv&#233;n', 'sname' => 'sierra-de-vaiven', 'isPri' => 'no'),
	'3' => array('name' => 'Mahjong', 'sname' => 'mahjong', 'isPri' => 'yes'),
	'4' => array('name' => 'Puzzle', 'sname' => 'puzzle', 'isPri' => 'yes'),
	'5' => array('name' => 'Cartas y Tablero', 'sname' => 'cartas-y-tablero', 'isPri' => 'yes'),
	'6' => array('name' => 'Palabras', 'sname' => 'palabras', 'isPri' =>  'yes'),
	'7' => array('name' => 'Multiplayer', 'sname' =>  'multiplayer', 'isPri' => 'no'),
	'9' => array('name' => 'Broadband', 'sname' => 'broadband', 'isPri' => 'no'),
	'10' => array('name' => 'Sports', 'sname' =>  'sports', 'isPri' => 'no'),
	'11' => array('name' => 'Casino', 'sname' => 'casino', 'isPri' => 'no'),
	'14' => array('name' => 'Game of the Year', 'sname' => 'game', 'isPri' => 'no'),
	'15' => array('name' => 'Objetos Ocultos', 'sname' => 'objetos-ocultos', 'isPri' => 'yes'),
	'16' => array('name' => 'Mac', 'sname' => 'mac', 'isPri' => 'no'),
	'17' => array('name' => 'Match 3', 'sname' => 'match-3', 'isPri' => 'yes'),
	'18' => array('name' => 'Destruir Bolas', 'sname' => 'destruir-bolas', 'isPri' => 'yes'),
	'19' => array('name' => 'Ingenio', 'sname' => 'ingenio', 'isPri' => 'yes'),
	'20' => array('name' => 'Gran Aventura', 'sname' => 'gran-aventura', 'isPri' => 'yes'),
	'21' => array('name' => 'Aventura', 'sname' => 'aventura', 'isPri' => 'yes'),
	'22' => array('name' => 'Brick Buster', 'sname' => 'brick', 'isPri' => 'no'),
	'23' => array('name' => 'Platformer', 'sname' => 'platformer', 'isPri' => 'no'),
	'24' => array('name' => 'Shooter', 'sname' => 'shooter', 'isPri' => 'no'),
	'25' => array('name' => 'Gestión del Tiempo', 'sname' => 'gestion-del-tiempo', 'isPri' => 'yes'),
	'26' => array('name' => 'Niños', 'sname' => 'ninos', 'isPri' => 'yes'),
	'27' => array('name' => 'Mystery', 'sname' => 'mystery', 'isPri' => 'no'),
	'29' => array('name' => 'Estrategia', 'sname' => 'estrategia', 'isPri' => 'yes'),
	'30' => array('name' => 'Reflexión', 'sname' => 'reflexion', 'isPri' => 'yes'),
	'31' => array('name' => '3D', 'sname' => '3d', 'isPri' => 'no'),
	'32' => array('name' => 'Animal', 'sname' => 'animal', 'isPri' => 'no'),
	'33' => array('name' => 'Baking', 'sname' => 'baking', 'isPri' => 'no'),
	'34' => array('name' => 'Beauty', 'sname' => 'beauty', 'isPri' => 'no'),
	'35' => array('name' => 'Book', 'sname' => 'book', 'isPri' => 'no'),
	'36' => array('name' => 'Bowling', 'sname' => 'bowling', 'isPri' => 'no'),
	'37' => array('name' => 'Breakout', 'sname' => 'breakout', 'isPri' => 'no'),
	'38' => array('name' => 'Building', 'sname' => 'building', 'isPri' => 'no'),
	'39' => array('name' => 'Burger', 'sname' => 'burger', 'isPri' => 'no'),
	'40' => array('name' => 'Candy', 'sname' => 'candy', 'isPri' => 'no'),
	'41' => array('name' => 'Cat', 'sname' => 'cat', 'isPri' => 'no'),
	'42' => array('name' => 'Chess', 'sname' => 'chess', 'isPri' => 'no'),
	'43' => array('name' => 'Chicken', 'sname' => 'chicken', 'isPri' => 'no'),
	'44' => array('name' => 'Childrens', 'sname' => 'childrens', 'isPri' => 'no'),
	'45' => array('name' => 'Christmas', 'sname' => 'christmas', 'isPri' => 'no'), 
	'46' => array('name' => 'Classic', 'sname' => 'classic', 'isPri' => 'no'),
	'47' => array('name' => 'Cooking', 'sname' => 'cooking', 'isPri' => 'no'),
	'48' => array('name' => 'Dancing', 'sname' => 'dancing', 'isPri' => 'no'),
	'49' => array('name' => 'Detective', 'sname' => 'detective', 'isPri' => 'no'),
	'50' => array('name' => 'Doctor', 'sname' => 'doctor', 'isPri' => 'no'),
	'51' => array('name' => 'Dog', 'sname' => 'dog', 'isPri' => 'no'),
	'52' => array('name' => 'Dominos', 'sname' => 'dominos', 'isPri' => 'no'),
	'53' => array('name' => 'Dragon', 'sname' => 'dragon', 'isPri' => 'no'),
	'54' => array('name' => 'Dress Up', 'sname' => 'dress_up', 'isPri' => 'no'),
	'55' => array('name' => 'Educational', 'sname' => 'educational', 'isPri' => 'no'),
	'56' => array('name' => 'Fairy', 'sname' => 'fairy', 'isPri' => 'no'),
	'57' => array('name' => 'Fantasy', 'sname' => 'fantasy', 'isPri' => 'no'),
	'58' => array('name' => 'Farm', 'sname' => 'farm', 'isPri' => 'no'),
	'59' => array('name' => 'Fashion', 'sname' => 'fashion', 'isPri' => 'no'),
	'60' => array('name' => 'Flower', 'sname' => 'flower', 'isPri' => 'no'),
	'61' => array('name' => 'Food', 'sname' => 'food', 'isPri' => 'no'),
	'62' => array('name' => 'Game Show', 'sname' => 'game_show', 'isPri' => 'no'),
	'63' => array('name' => 'Garden', 'sname' => 'garden', 'isPri' => 'no'),
	'64' => array('name' => 'Holiday', 'sname' => 'holiday', 'isPri' => 'no'),
	'65' => array('name' => 'Hotel', 'sname' => 'hotel', 'isPri' => 'no'),
	'66' => array('name' => 'Ice Cream', 'sname' => 'ice_cream', 'isPri' => 'no'),
	'67' => array('name' => 'Interior Design', 'sname' => 'interior_design', 'isPri' => 'no'),
	'68' => array('name' => 'Jewelry', 'sname' => 'jewelry', 'isPri' => 'no'),
	'69' => array('name' => 'Magic', 'sname' => 'magic', 'isPri' => 'no'),
	'70' => array('name' => 'Monster', 'sname' => 'monster', 'isPri' => 'no'),
	'71' => array('name' => 'Music', 'sname' => 'music', 'isPri' => 'no'),
	'72' => array('name' => 'Pet', 'sname' => 'pet', 'isPri' => 'no'),
	'73' => array('name' => 'Pirate', 'sname' => 'pirate', 'isPri' => 'no'),
	'74' => array('name' => 'Plant', 'sname' => 'plant', 'isPri' => 'no'),
	'75' => array('name' => 'Point And Click', 'sname' => 'point_and_click', 'isPri' => 'no'),
	'76' => array('name' => 'Poker', 'sname' => 'poker', 'isPri' => 'no'),
	'77' => array('name' => 'Princess', 'sname' => 'princess', 'isPri' => 'no'),
	'78' => array('name' => 'Quest', 'sname' => 'quest', 'isPri' => 'no'),
	'79' => array('name' => 'Racing', 'sname' => 'racing', 'isPri' => 'no'),
	'80' => array('name' => 'Real Time', 'sname' => 'real_time', 'isPri' => 'no'),
	'81' => array('name' => 'Restaurant', 'sname' => 'restaurant', 'isPri' => 'no'),
	'82' => array('name' => 'Rpg', 'sname' => 'rpg', 'isPri' => 'no'),
	'83' => array('name' => 'Seek And Find', 'sname' => 'seek_and_find', 'isPri' => 'no'),
	'84' => array('name' => 'Sim', 'sname' => 'sim', 'isPri' => 'no'),
	'85' => array('name' => 'Solitaire', 'sname' => 'solitaire', 'isPri' => 'no'),
	'86' => array('name' => 'Spa', 'sname' => 'spa', 'isPri' => 'no'),
	'87' => array('name' => 'Space', 'sname' => 'space', 'isPri' => 'no'),
	'88' => array('name' => 'Sudoku', 'sname' => 'sudoku', 'isPri' => 'no'),
	'89' => array('name' => 'Tower Defense', 'sname' => 'tower_defense', 'isPri' => 'no'),
	'90' => array('name' => 'Travel', 'sname' => 'travel', 'isPri' => 'no'),
	'91' => array('name' => 'Treasure', 'sname' => 'treasure', 'isPri' => 'no'),
	'92' => array('name' => 'Trivia', 'sname' => 'trivia', 'isPri' => 'no'),
	'93' => array('name' => 'Tv Show', 'sname' => 'tv_show', 'isPri' => 'no'),
	'94' => array('name' => 'Tycoon', 'sname' => 'tycoon', 'isPri' => 'no'),
	'95' => array('name' => 'War', 'sname' => 'war', 'isPri' => 'no'),
	'96' => array('name' => 'Water', 'sname' => 'water', 'isPri' => 'no'),
	'97' => array('name' => 'Wedding', 'sname' => 'wedding', 'isPri' => 'no'),
	'98' => array('name' => 'Zoo', 'sname' => 'zoo', 'isPri' => 'no'),
	'99' => array('name' => 'Agatha Christie', 'sname' => 'agatha_christie', 'isPri' => 'no'),
	'100' => array('name' => 'Aveyond', 'sname' => 'aveyond', 'isPri' => 'no'),
	'101' => array('name' => 'Beetle Bug', 'sname' => 'beetle_bug', 'isPri' => 'no'),
	'102' => array('name' => 'Diner Dash', 'sname' => 'diner_dash', 'isPri' => 'no'),
	'103' => array('name' => 'Dora The Explorer', 'sname' => 'dora_the_explorer', 'isPri' => 'no'),
	'104' => array('name' => 'Dream Day', 'sname' => 'dream_day', 'isPri' => 'no'),
	'105' => array('name' => 'Luxor', 'sname' => 'luxor', 'isPri' => 'no'),
	'106' => array('name' => 'Nancy Drew', 'sname' => 'nancy_drew', 'isPri' => 'no'),
	'107' => array('name' => 'Pat Sajak', 'sname' => 'pat_sajak', 'isPri' => 'no'),
	'108' => array('name' => 'Ricochet', 'sname' => 'ricochet', 'isPri' => 'no'),
	'109' => array('name' => 'Sherlock Holmes', 'sname' => 'sherlock_holmes', 'isPri' => 'no'),
	'110' => array('name' => 'Sims Carnival', 'sname' => 'sims_carnival', 'isPri' => 'no'),
	'111' => array('name' => 'Slingo', 'sname' => 'slingo', 'isPri' => 'no'),
	'112' => array('name' => 'Spongebob', 'sname' => 'spongebob', 'isPri' => 'no'),
	'113' => array('name' => 'Tri Peaks', 'sname' => 'tri_peaks', 'isPri' => 'no'),
	'114' => array('name' => 'Virtual Villagers', 'sname' => 'virtual_villagers', 'isPri' => 'no'),
	'115' => array('name' => 'Azada', 'sname' => 'azada', 'isPri' => 'no'),
	'116' => array('name' => 'Hidden Expedition', 'sname' => 'hidden_expedition', 'isPri' => 'no'),
	'117' => array('name' => 'Mystery Case Files', 'sname' => 'mystery_case_files', 'isPri' => 'no'),
	'118' => array('name' => 'Best PC', 'sname' => 'best_pc', 'isPri' => 'no'),
	'119' => array('name' => 'Exclusive', 'sname' => 'exclusive', 'isPri' => 'no')
);

$bfg_genres_fr = array(
	'1' => array('name' => 'Action & Arcade', 'sname' => 'action', 'isPri' => 'yes'),
	'2' => array('name' => 'Scie sauteuse', 'sname' => 'scie-sauteuse', 'isPri' => 'yes'),
	'3' => array('name' => 'Mahjong', 'sname' => 'mahjong', 'isPri' => 'yes'),
	'4' => array('name' => 'Puzzle', 'sname' => 'puzzle', 'isPri' => 'yes'),
	'5' => array('name' => 'Cartes & Plateau', 'sname' => 'card', 'isPri' => 'yes'),
	'6' => array('name' => 'Mots', 'sname' => 'word', 'isPri' =>  'yes'),
	'7' => array('name' => 'Multiplayer', 'sname' =>  'multiplayer', 'isPri' => 'no'),
	'9' => array('name' => 'Broadband', 'sname' => 'broadband', 'isPri' => 'no'),
	'10' => array('name' => 'Sports', 'sname' =>  'sports', 'isPri' => 'no'),
	'11' => array('name' => 'Casino', 'sname' => 'casino', 'isPri' => 'no'),
	'14' => array('name' => 'Game of the Year', 'sname' => 'game', 'isPri' => 'no'),
	'15' => array('name' => 'Objets cachés', 'sname' => 'hidden', 'isPri' => 'yes'),
	'16' => array('name' => 'Mac', 'sname' => 'mac', 'isPri' => 'no'),
	'17' => array('name' => 'Match 3', 'sname' => 'match3', 'isPri' => 'yes'),
	'18' => array('name' => 'Destruction de billes', 'sname' => 'marble', 'isPri' => 'yes'),
	'19' => array('name' => 'Casse-tête', 'sname' => 'brain', 'isPri' => 'yes'),
	'20' => array('name' => 'Grande aventure', 'sname' => 'adventure_large', 'isPri' => 'yes'),
	'21' => array('name' => 'Aventure', 'sname' => 'adventure', 'isPri' => 'yes'),
	'22' => array('name' => 'Brick Buster', 'sname' => 'brick', 'isPri' => 'no'),
	'23' => array('name' => 'Platformer', 'sname' => 'platformer', 'isPri' => 'no'),
	'24' => array('name' => 'Shooter', 'sname' => 'shooter', 'isPri' => 'no'),
	'25' => array('name' => 'Gestion du temps', 'sname' => 'time', 'isPri' => 'yes'),
	'26' => array('name' => 'Enfants', 'sname' => 'kids', 'isPri' => 'yes'),
	'27' => array('name' => 'Mystery', 'sname' => 'mystery', 'isPri' => 'no'),
	'29' => array('name' => 'Stratégie', 'sname' => 'strategy', 'isPri' => 'yes'),
	'30' => array('name' => 'Réflexion', 'sname' => 'riddle', 'isPri' => 'yes'),
	'31' => array('name' => '3D', 'sname' => '3d', 'isPri' => 'no'),
	'32' => array('name' => 'Animal', 'sname' => 'animal', 'isPri' => 'no'),
	'33' => array('name' => 'Baking', 'sname' => 'baking', 'isPri' => 'no'),
	'34' => array('name' => 'Beauty', 'sname' => 'beauty', 'isPri' => 'no'),
	'35' => array('name' => 'Book', 'sname' => 'book', 'isPri' => 'no'),
	'36' => array('name' => 'Bowling', 'sname' => 'bowling', 'isPri' => 'no'),
	'37' => array('name' => 'Breakout', 'sname' => 'breakout', 'isPri' => 'no'),
	'38' => array('name' => 'Building', 'sname' => 'building', 'isPri' => 'no'),
	'39' => array('name' => 'Burger', 'sname' => 'burger', 'isPri' => 'no'),
	'40' => array('name' => 'Candy', 'sname' => 'candy', 'isPri' => 'no'),
	'41' => array('name' => 'Cat', 'sname' => 'cat', 'isPri' => 'no'),
	'42' => array('name' => 'Chess', 'sname' => 'chess', 'isPri' => 'no'),
	'43' => array('name' => 'Chicken', 'sname' => 'chicken', 'isPri' => 'no'),
	'44' => array('name' => 'Childrens', 'sname' => 'childrens', 'isPri' => 'no'),
	'45' => array('name' => 'Christmas', 'sname' => 'christmas', 'isPri' => 'no'), 
	'46' => array('name' => 'Classic', 'sname' => 'classic', 'isPri' => 'no'),
	'47' => array('name' => 'Cooking', 'sname' => 'cooking', 'isPri' => 'no'),
	'48' => array('name' => 'Dancing', 'sname' => 'dancing', 'isPri' => 'no'),
	'49' => array('name' => 'Detective', 'sname' => 'detective', 'isPri' => 'no'),
	'50' => array('name' => 'Doctor', 'sname' => 'doctor', 'isPri' => 'no'),
	'51' => array('name' => 'Dog', 'sname' => 'dog', 'isPri' => 'no'),
	'52' => array('name' => 'Dominos', 'sname' => 'dominos', 'isPri' => 'no'),
	'53' => array('name' => 'Dragon', 'sname' => 'dragon', 'isPri' => 'no'),
	'54' => array('name' => 'Dress Up', 'sname' => 'dress_up', 'isPri' => 'no'),
	'55' => array('name' => 'Educational', 'sname' => 'educational', 'isPri' => 'no'),
	'56' => array('name' => 'Fairy', 'sname' => 'fairy', 'isPri' => 'no'),
	'57' => array('name' => 'Fantasy', 'sname' => 'fantasy', 'isPri' => 'no'),
	'58' => array('name' => 'Farm', 'sname' => 'farm', 'isPri' => 'no'),
	'59' => array('name' => 'Fashion', 'sname' => 'fashion', 'isPri' => 'no'),
	'60' => array('name' => 'Flower', 'sname' => 'flower', 'isPri' => 'no'),
	'61' => array('name' => 'Food', 'sname' => 'food', 'isPri' => 'no'),
	'62' => array('name' => 'Game Show', 'sname' => 'game_show', 'isPri' => 'no'),
	'63' => array('name' => 'Garden', 'sname' => 'garden', 'isPri' => 'no'),
	'64' => array('name' => 'Holiday', 'sname' => 'holiday', 'isPri' => 'no'),
	'65' => array('name' => 'Hotel', 'sname' => 'hotel', 'isPri' => 'no'),
	'66' => array('name' => 'Ice Cream', 'sname' => 'ice_cream', 'isPri' => 'no'),
	'67' => array('name' => 'Interior Design', 'sname' => 'interior_design', 'isPri' => 'no'),
	'68' => array('name' => 'Jewelry', 'sname' => 'jewelry', 'isPri' => 'no'),
	'69' => array('name' => 'Magic', 'sname' => 'magic', 'isPri' => 'no'),
	'70' => array('name' => 'Monster', 'sname' => 'monster', 'isPri' => 'no'),
	'71' => array('name' => 'Music', 'sname' => 'music', 'isPri' => 'no'),
	'72' => array('name' => 'Pet', 'sname' => 'pet', 'isPri' => 'no'),
	'73' => array('name' => 'Pirate', 'sname' => 'pirate', 'isPri' => 'no'),
	'74' => array('name' => 'Plant', 'sname' => 'plant', 'isPri' => 'no'),
	'75' => array('name' => 'Point And Click', 'sname' => 'point_and_click', 'isPri' => 'no'),
	'76' => array('name' => 'Poker', 'sname' => 'poker', 'isPri' => 'no'),
	'77' => array('name' => 'Princess', 'sname' => 'princess', 'isPri' => 'no'),
	'78' => array('name' => 'Quest', 'sname' => 'quest', 'isPri' => 'no'),
	'79' => array('name' => 'Racing', 'sname' => 'racing', 'isPri' => 'no'),
	'80' => array('name' => 'Real Time', 'sname' => 'real_time', 'isPri' => 'no'),
	'81' => array('name' => 'Restaurant', 'sname' => 'restaurant', 'isPri' => 'no'),
	'82' => array('name' => 'Rpg', 'sname' => 'rpg', 'isPri' => 'no'),
	'83' => array('name' => 'Seek And Find', 'sname' => 'seek_and_find', 'isPri' => 'no'),
	'84' => array('name' => 'Sim', 'sname' => 'sim', 'isPri' => 'no'),
	'85' => array('name' => 'Solitaire', 'sname' => 'solitaire', 'isPri' => 'no'),
	'86' => array('name' => 'Spa', 'sname' => 'spa', 'isPri' => 'no'),
	'87' => array('name' => 'Space', 'sname' => 'space', 'isPri' => 'no'),
	'88' => array('name' => 'Sudoku', 'sname' => 'sudoku', 'isPri' => 'no'),
	'89' => array('name' => 'Tower Defense', 'sname' => 'tower_defense', 'isPri' => 'no'),
	'90' => array('name' => 'Travel', 'sname' => 'travel', 'isPri' => 'no'),
	'91' => array('name' => 'Treasure', 'sname' => 'treasure', 'isPri' => 'no'),
	'92' => array('name' => 'Trivia', 'sname' => 'trivia', 'isPri' => 'no'),
	'93' => array('name' => 'Tv Show', 'sname' => 'tv_show', 'isPri' => 'no'),
	'94' => array('name' => 'Tycoon', 'sname' => 'tycoon', 'isPri' => 'no'),
	'95' => array('name' => 'War', 'sname' => 'war', 'isPri' => 'no'),
	'96' => array('name' => 'Water', 'sname' => 'water', 'isPri' => 'no'),
	'97' => array('name' => 'Wedding', 'sname' => 'wedding', 'isPri' => 'no'),
	'98' => array('name' => 'Zoo', 'sname' => 'zoo', 'isPri' => 'no'),
	'99' => array('name' => 'Agatha Christie', 'sname' => 'agatha_christie', 'isPri' => 'no'),
	'100' => array('name' => 'Aveyond', 'sname' => 'aveyond', 'isPri' => 'no'),
	'101' => array('name' => 'Beetle Bug', 'sname' => 'beetle_bug', 'isPri' => 'no'),
	'102' => array('name' => 'Diner Dash', 'sname' => 'diner_dash', 'isPri' => 'no'),
	'103' => array('name' => 'Dora The Explorer', 'sname' => 'dora_the_explorer', 'isPri' => 'no'),
	'104' => array('name' => 'Dream Day', 'sname' => 'dream_day', 'isPri' => 'no'),
	'105' => array('name' => 'Luxor', 'sname' => 'luxor', 'isPri' => 'no'),
	'106' => array('name' => 'Nancy Drew', 'sname' => 'nancy_drew', 'isPri' => 'no'),
	'107' => array('name' => 'Pat Sajak', 'sname' => 'pat_sajak', 'isPri' => 'no'),
	'108' => array('name' => 'Ricochet', 'sname' => 'ricochet', 'isPri' => 'no'),
	'109' => array('name' => 'Sherlock Holmes', 'sname' => 'sherlock_holmes', 'isPri' => 'no'),
	'110' => array('name' => 'Sims Carnival', 'sname' => 'sims_carnival', 'isPri' => 'no'),
	'111' => array('name' => 'Slingo', 'sname' => 'slingo', 'isPri' => 'no'),
	'112' => array('name' => 'Spongebob', 'sname' => 'spongebob', 'isPri' => 'no'),
	'113' => array('name' => 'Tri Peaks', 'sname' => 'tri_peaks', 'isPri' => 'no'),
	'114' => array('name' => 'Virtual Villagers', 'sname' => 'virtual_villagers', 'isPri' => 'no'),
	'115' => array('name' => 'Azada', 'sname' => 'azada', 'isPri' => 'no'),
	'116' => array('name' => 'Hidden Expedition', 'sname' => 'hidden_expedition', 'isPri' => 'no'),
	'117' => array('name' => 'Mystery Case Files', 'sname' => 'mystery_case_files', 'isPri' => 'no'),
	'118' => array('name' => 'Best PC', 'sname' => 'best_pc', 'isPri' => 'no'),
	'119' => array('name' => 'Exclusive', 'sname' => 'exclusive', 'isPri' => 'no')
);

$bfg_genres_jp = array(
	'1' => array('name' => 'アーケード &amp; アクション ゲーム', 'sname' => 'action', 'isPri' => 'yes'),
	'2' => array('name' => 'Jigsaw', 'sname' => 'jigsaw', 'isPri' => 'no'),
	'3' => array('name' => '麻雀 & 上海 ゲーム', 'sname' => 'mahjong', 'isPri' => 'yes'),
	'4' => array('name' => 'パズル ゲーム', 'sname' => 'puzzle', 'isPri' => 'yes'),
	'5' => array('name' => 'Card & Board', 'sname' => 'card', 'isPri' => 'yes'),
	'6' => array('name' => 'Word', 'sname' => 'word', 'isPri' =>  'yes'),
	'7' => array('name' => 'Multiplayer', 'sname' =>  'multiplayer', 'isPri' => 'no'),
	'9' => array('name' => 'Broadband', 'sname' => 'broadband', 'isPri' => 'no'),
	'10' => array('name' => 'Sports', 'sname' =>  'sports', 'isPri' => 'no'),
	'11' => array('name' => 'Casino', 'sname' => 'casino', 'isPri' => 'no'),
	'14' => array('name' => 'Game of the Year', 'sname' => 'game', 'isPri' => 'no'),
	'15' => array('name' => 'アイテム探し ゲーム', 'sname' => 'hidden', 'isPri' => 'yes'),
	'16' => array('name' => 'Mac', 'sname' => 'mac', 'isPri' => 'no'),
	'17' => array('name' => 'マッチ 3 ゲーム', 'sname' => 'match3', 'isPri' => 'yes'),
	'18' => array('name' => 'ビー玉ポッパー ゲーム', 'sname' => 'marble', 'isPri' => 'yes'),
	'19' => array('name' => '頭の体操 ゲーム', 'sname' => 'brain', 'isPri' => 'yes'),
	'20' => array('name' => 'Large File Adventure', 'sname' => 'adventure_large', 'isPri' => 'yes'),
	'21' => array('name' => 'アドベンチャー ゲーム', 'sname' => 'adventure', 'isPri' => 'yes'),
	'22' => array('name' => 'Brick Buster', 'sname' => 'brick', 'isPri' => 'no'),
	'23' => array('name' => 'Platformer', 'sname' => 'platformer', 'isPri' => 'no'),
	'24' => array('name' => 'Shooter', 'sname' => 'shooter', 'isPri' => 'no'),
	'25' => array('name' => 'タイム マネージメント ゲーム', 'sname' => 'time', 'isPri' => 'yes'),
	'26' => array('name' => 'Kids', 'sname' => 'kids', 'isPri' => 'yes'),
	'27' => array('name' => 'Mystery', 'sname' => 'mystery', 'isPri' => 'no'),
	'29' => array('name' => 'Strategy', 'sname' => 'strategy', 'isPri' => 'yes'),
	'30' => array('name' => 'Riddle', 'sname' => 'riddle', 'isPri' => 'yes'),
	'31' => array('name' => '3D', 'sname' => '3d', 'isPri' => 'no'),
	'32' => array('name' => 'Animal', 'sname' => 'animal', 'isPri' => 'no'),
	'33' => array('name' => 'Baking', 'sname' => 'baking', 'isPri' => 'no'),
	'34' => array('name' => 'Beauty', 'sname' => 'beauty', 'isPri' => 'no'),
	'35' => array('name' => 'Book', 'sname' => 'book', 'isPri' => 'no'),
	'36' => array('name' => 'Bowling', 'sname' => 'bowling', 'isPri' => 'no'),
	'37' => array('name' => 'Breakout', 'sname' => 'breakout', 'isPri' => 'no'),
	'38' => array('name' => 'Building', 'sname' => 'building', 'isPri' => 'no'),
	'39' => array('name' => 'Burger', 'sname' => 'burger', 'isPri' => 'no'),
	'40' => array('name' => 'Candy', 'sname' => 'candy', 'isPri' => 'no'),
	'41' => array('name' => 'Cat', 'sname' => 'cat', 'isPri' => 'no'),
	'42' => array('name' => 'Chess', 'sname' => 'chess', 'isPri' => 'no'),
	'43' => array('name' => 'Chicken', 'sname' => 'chicken', 'isPri' => 'no'),
	'44' => array('name' => 'Childrens', 'sname' => 'childrens', 'isPri' => 'no'),
	'45' => array('name' => 'Christmas', 'sname' => 'christmas', 'isPri' => 'no'), 
	'46' => array('name' => 'Classic', 'sname' => 'classic', 'isPri' => 'no'),
	'47' => array('name' => 'Cooking', 'sname' => 'cooking', 'isPri' => 'no'),
	'48' => array('name' => 'Dancing', 'sname' => 'dancing', 'isPri' => 'no'),
	'49' => array('name' => 'Detective', 'sname' => 'detective', 'isPri' => 'no'),
	'50' => array('name' => 'Doctor', 'sname' => 'doctor', 'isPri' => 'no'),
	'51' => array('name' => 'Dog', 'sname' => 'dog', 'isPri' => 'no'),
	'52' => array('name' => 'Dominos', 'sname' => 'dominos', 'isPri' => 'no'),
	'53' => array('name' => 'Dragon', 'sname' => 'dragon', 'isPri' => 'no'),
	'54' => array('name' => 'Dress Up', 'sname' => 'dress_up', 'isPri' => 'no'),
	'55' => array('name' => 'Educational', 'sname' => 'educational', 'isPri' => 'no'),
	'56' => array('name' => 'Fairy', 'sname' => 'fairy', 'isPri' => 'no'),
	'57' => array('name' => 'Fantasy', 'sname' => 'fantasy', 'isPri' => 'no'),
	'58' => array('name' => 'Farm', 'sname' => 'farm', 'isPri' => 'no'),
	'59' => array('name' => 'Fashion', 'sname' => 'fashion', 'isPri' => 'no'),
	'60' => array('name' => 'Flower', 'sname' => 'flower', 'isPri' => 'no'),
	'61' => array('name' => 'Food', 'sname' => 'food', 'isPri' => 'no'),
	'62' => array('name' => 'Game Show', 'sname' => 'game_show', 'isPri' => 'no'),
	'63' => array('name' => 'Garden', 'sname' => 'garden', 'isPri' => 'no'),
	'64' => array('name' => 'Holiday', 'sname' => 'holiday', 'isPri' => 'no'),
	'65' => array('name' => 'Hotel', 'sname' => 'hotel', 'isPri' => 'no'),
	'66' => array('name' => 'Ice Cream', 'sname' => 'ice_cream', 'isPri' => 'no'),
	'67' => array('name' => 'Interior Design', 'sname' => 'interior_design', 'isPri' => 'no'),
	'68' => array('name' => 'Jewelry', 'sname' => 'jewelry', 'isPri' => 'no'),
	'69' => array('name' => 'Magic', 'sname' => 'magic', 'isPri' => 'no'),
	'70' => array('name' => 'Monster', 'sname' => 'monster', 'isPri' => 'no'),
	'71' => array('name' => 'Music', 'sname' => 'music', 'isPri' => 'no'),
	'72' => array('name' => 'Pet', 'sname' => 'pet', 'isPri' => 'no'),
	'73' => array('name' => 'Pirate', 'sname' => 'pirate', 'isPri' => 'no'),
	'74' => array('name' => 'Plant', 'sname' => 'plant', 'isPri' => 'no'),
	'75' => array('name' => 'Point And Click', 'sname' => 'point_and_click', 'isPri' => 'no'),
	'76' => array('name' => 'Poker', 'sname' => 'poker', 'isPri' => 'no'),
	'77' => array('name' => 'Princess', 'sname' => 'princess', 'isPri' => 'no'),
	'78' => array('name' => 'Quest', 'sname' => 'quest', 'isPri' => 'no'),
	'79' => array('name' => 'Racing', 'sname' => 'racing', 'isPri' => 'no'),
	'80' => array('name' => 'Real Time', 'sname' => 'real_time', 'isPri' => 'no'),
	'81' => array('name' => 'Restaurant', 'sname' => 'restaurant', 'isPri' => 'no'),
	'82' => array('name' => 'Rpg', 'sname' => 'rpg', 'isPri' => 'no'),
	'83' => array('name' => 'Seek And Find', 'sname' => 'seek_and_find', 'isPri' => 'no'),
	'84' => array('name' => 'Sim', 'sname' => 'sim', 'isPri' => 'no'),
	'85' => array('name' => 'Solitaire', 'sname' => 'solitaire', 'isPri' => 'no'),
	'86' => array('name' => 'Spa', 'sname' => 'spa', 'isPri' => 'no'),
	'87' => array('name' => 'Space', 'sname' => 'space', 'isPri' => 'no'),
	'88' => array('name' => 'Sudoku', 'sname' => 'sudoku', 'isPri' => 'no'),
	'89' => array('name' => 'Tower Defense', 'sname' => 'tower_defense', 'isPri' => 'no'),
	'90' => array('name' => 'Travel', 'sname' => 'travel', 'isPri' => 'no'),
	'91' => array('name' => 'Treasure', 'sname' => 'treasure', 'isPri' => 'no'),
	'92' => array('name' => 'Trivia', 'sname' => 'trivia', 'isPri' => 'no'),
	'93' => array('name' => 'Tv Show', 'sname' => 'tv_show', 'isPri' => 'no'),
	'94' => array('name' => 'Tycoon', 'sname' => 'tycoon', 'isPri' => 'no'),
	'95' => array('name' => 'War', 'sname' => 'war', 'isPri' => 'no'),
	'96' => array('name' => 'Water', 'sname' => 'water', 'isPri' => 'no'),
	'97' => array('name' => 'Wedding', 'sname' => 'wedding', 'isPri' => 'no'),
	'98' => array('name' => 'Zoo', 'sname' => 'zoo', 'isPri' => 'no'),
	'99' => array('name' => 'Agatha Christie', 'sname' => 'agatha_christie', 'isPri' => 'no'),
	'100' => array('name' => 'Aveyond', 'sname' => 'aveyond', 'isPri' => 'no'),
	'101' => array('name' => 'Beetle Bug', 'sname' => 'beetle_bug', 'isPri' => 'no'),
	'102' => array('name' => 'Diner Dash', 'sname' => 'diner_dash', 'isPri' => 'no'),
	'103' => array('name' => 'Dora The Explorer', 'sname' => 'dora_the_explorer', 'isPri' => 'no'),
	'104' => array('name' => 'Dream Day', 'sname' => 'dream_day', 'isPri' => 'no'),
	'105' => array('name' => 'Luxor', 'sname' => 'luxor', 'isPri' => 'no'),
	'106' => array('name' => 'Nancy Drew', 'sname' => 'nancy_drew', 'isPri' => 'no'),
	'107' => array('name' => 'Pat Sajak', 'sname' => 'pat_sajak', 'isPri' => 'no'),
	'108' => array('name' => 'Ricochet', 'sname' => 'ricochet', 'isPri' => 'no'),
	'109' => array('name' => 'Sherlock Holmes', 'sname' => 'sherlock_holmes', 'isPri' => 'no'),
	'110' => array('name' => 'Sims Carnival', 'sname' => 'sims_carnival', 'isPri' => 'no'),
	'111' => array('name' => 'Slingo', 'sname' => 'slingo', 'isPri' => 'no'),
	'112' => array('name' => 'Spongebob', 'sname' => 'spongebob', 'isPri' => 'no'),
	'113' => array('name' => 'Tri Peaks', 'sname' => 'tri_peaks', 'isPri' => 'no'),
	'114' => array('name' => 'Virtual Villagers', 'sname' => 'virtual_villagers', 'isPri' => 'no'),
	'115' => array('name' => 'Azada', 'sname' => 'azada', 'isPri' => 'no'),
	'116' => array('name' => 'Hidden Expedition', 'sname' => 'hidden_expedition', 'isPri' => 'no'),
	'117' => array('name' => 'Mystery Case Files', 'sname' => 'mystery_case_files', 'isPri' => 'no'),
	'118' => array('name' => 'Best PC', 'sname' => 'best_pc', 'isPri' => 'no'),
	'119' => array('name' => 'Exclusive', 'sname' => 'exclusive', 'isPri' => 'no'),
	'121' => array('name' => '英語版 ゲーム', 'sname' => 'english-games', 'isPri' => 'yes')
);


?>
